import { Hono } from "hono";
import { jwt } from "hono/jwt";
import db from "../db";
import { generatePDF } from "../services/pdf";

const portal = new Hono();
const SECRET = process.env.JWT_SECRET || "ASTRAKE_EMS_SECRET_KEY_2025";

// Middleware to protect all routes
portal.use("/*", jwt({ secret: SECRET }));

// Profile
portal.get("/me", (c) => {
    const payload = c.get("jwtPayload");
    const emp = db.query(`
        SELECT id, name, skill_type, daily_wage, uan, pf_applicable, esi_applicable, gp_number, active, username 
        FROM employees WHERE id = ?
    `).get(payload.id);

    if (!emp) return c.json({ error: "Not found" }, 404);
    return c.json(emp);
});

// Attendance History
portal.get("/attendance", (c) => {
    const payload = c.get("jwtPayload");
    // History of billing periods where this employee is present
    const history = db.query(`
        SELECT 
            be.days_worked, be.wage_amount,
            bp.from_date, bp.to_date, bp.label,
            p.site_name, p.client_name,
            bp.id as billing_period_id
        FROM billing_employees be
        JOIN billing_periods bp ON be.billing_period_id = bp.id
        JOIN projects p ON bp.project_id = p.id
        WHERE be.employee_id = ?
        ORDER BY bp.from_date DESC
    `).all(payload.id);
    return c.json(history);
});

// Simple Payslip Generation on the fly
portal.get("/payslip/:id", async (c) => {
    const payload = c.get("jwtPayload");
    const billingPeriodId = c.req.param("id");

    const record = db.query(`
        SELECT 
            be.*, 
            e.name as emp_name, e.uan, e.gp_number, e.skill_type, e.daily_wage,
            bp.from_date, bp.to_date, 
            p.site_name, p.client_name, p.work_order_no
        FROM billing_employees be
        JOIN employees e ON be.employee_id = e.id
        JOIN billing_periods bp ON be.billing_period_id = bp.id
        JOIN projects p ON bp.project_id = p.id
        WHERE be.employee_id = ? AND be.billing_period_id = ?
    `).get(payload.id, billingPeriodId) as any;

    if (!record) return c.json({ error: "Record not found" }, 404);

    // Simple HTML Template
    const html = `
    <html>
    <head>
      <style>
        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1e293b; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; }
        .row { display: flex; justify-content: space-between; margin-bottom: 12px; }
        .label { font-weight: bold; color: #64748b; font-size: 14px; text-transform: uppercase; }
        .value { font-weight: bold; font-size: 16px; }
        .box { border: 1px solid #e2e8f0; padding: 24px; border-radius: 12px; margin-top: 24px; background: #f8fafc; }
        .amount { font-size: 32px; color: #2563EB; text-align: right; margin-top: 24px; font-weight: 900; }
        h1 { margin: 0 0 10px 0; color: #0f172a; }
        p { margin: 0; color: #475569; }
        .meta { font-size: 12px; color: #94a3b8; text-align: center; margin-top: 60px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>PAYSLIP</h1>
        <p>${record.client_name}</p>
        <p style="font-weight: bold; margin-top: 5px;">${record.site_name}</p>
        <p style="font-size: 14px; margin-top: 10px;">Period: ${new Date(record.from_date).toLocaleDateString()} to ${new Date(record.to_date).toLocaleDateString()}</p>
      </div>

      <div class="box">
        <div class="row"><span class="label">Employee Name</span> <span class="value">${record.emp_name}</span></div>
        <div class="row"><span class="label">Role</span> <span class="value">${record.skill_type.toUpperCase()}</span></div>
        <div class="row"><span class="label">ID/UAN</span> <span class="value">${record.uan || 'N/A'}</span></div>
        <div class="row"><span class="label">GP Number</span> <span class="value">${record.gp_number || 'N/A'}</span></div>
      </div>

      <div class="box" style="background: #fff; border-color: #cbd5e1;">
        <div class="row"><span class="label">Days Worked</span> <span class="value">${record.days_worked} Days</span></div>
        <div class="row"><span class="label">Daily Rate</span> <span class="value">₹${record.daily_wage}</span></div>
        <hr style="border: 0; border-top: 1px dashed #cbd5e1; margin: 20px 0;">
        <div class="amount">
          ₹${record.wage_amount.toLocaleString()}
        </div>
        <div style="text-align: right; font-size: 12px; color: #64748b; font-weight: bold; text-transform: uppercase;">Total Payable</div>
      </div>
      
      <div class="meta">Generated by Astrake EMS • ${new Date().toLocaleString()}</div>
    </body>
    </html>
    `;

    try {
        const pdfBytes = await generatePDF(html);
        c.header("Content-Type", "application/pdf");
        c.header("Content-Disposition", `attachment; filename="Payslip_${record.from_date}.pdf"`);
        return c.body(pdfBytes as any);
    } catch (e) {
        console.error(e);
        return c.json({ error: "Generation failed" }, 500);
    }
});

export default portal;
